### ISSUE TITLE
Microcontroller reboots when going to Flight mode with RS41 unpugged

### ISSUE THREAD

**Issue by kalnajslab** [MisterMartin/StratoCore_LPC#8]
When you put the LPC in flight mode with the RS41 disconnected (presumably also if the RS41 has failed) then the LPC reboots.  I suspect this is due to a timeout in the serial read from the RS41.

**Comment by MisterMartin** [comment]
The default timeout on the serial line, combined with repeat polling for RS41 meta data, caused the watchdog to trigger.

Fixed in the RS41 repository: https://github.com/MisterMartin/RS41/commit/d24f96a64b4640b13d6620da23e194da8beb0a3b
