### ISSUE TITLE
LPC record timestamp is not incrementing. 

### ISSUE THREAD

**Issue by kalnajslab** [MisterMartin/StratoCore_LPC#9]
In the LPC TM files, the differential timestamp for each record relative to the start of measurement time is almost always zero - so every record gets assigned the same time as start of measurement.

**Comment by MisterMartin** [comment]
MeasurementStartTime is being updated every time FL_MEASURE is being entered. Needs to have logic where it is updated only when a new measurement is initiated.

Bug was introduced in 60fb5eed687f77.

**Comment by MisterMartin** [comment]
Fixed in b64b5e626.
